import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(process.env.NOTIFYCONTEXT_TEST_URL);
 await page.getByText('Local test sign-in').click();
 await page.getByLabel('Email',{exact:true}).fill('bob@example.com');
 await page.getByLabel('Password',{exact:true}).fill('SyntheticUserPassword123!');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.locator('#connection').filter({hasText:'Connected'}).waitFor();
 const peer=await page.context().newPage();
 await peer.goto(process.env.NOTIFYCONTEXT_TEST_URL);
 await peer.locator('#connection').filter({hasText:'Connected'}).waitFor();
 await peer.reload();await peer.locator('#connection').filter({hasText:'Connected'}).waitFor();
 await peer.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.getByRole('button',{name:'Continue with Google'}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Continue with Google'}).waitFor();
 await page.getByText('Local test sign-in').click();
 await page.getByLabel('Email',{exact:true}).fill('bob@example.com');
 await page.getByLabel('Password',{exact:true}).fill('SyntheticUserPassword123!');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await peer.locator('#connection').filter({hasText:'Connected'}).waitFor();
 await expect(peer).toHaveTitle('(1) NotifyContext');
 await page.getByRole('heading',{name:'Supplier renewal ready',exact:true}).click();
 await page.locator('article strong').filter({hasText:'terms'}).waitFor();
 await page.getByRole('button',{name:'Mark read',exact:true}).click();
 await page.getByRole('button',{name:'Mark read',exact:true}).waitFor({state:'detached'});
 // A separate open tab must receive the committed change before fallback polling.
 await expect(peer).toHaveTitle('NotifyContext',{timeout:5000});await peer.close();
 await page.getByLabel('Optional acknowledgement note').fill('Received; reviewing this afternoon.');
 await page.getByRole('button',{name:'Acknowledge',exact:true}).click();
 await page.locator('.acknowledgement').filter({hasText:'Received; reviewing this afternoon.'}).waitFor();
 await page.getByRole('button',{name:'New notification'}).click();
 await page.getByLabel('To',{exact:true}).selectOption(process.env.NOTIFYCONTEXT_TEST_ALICE);
 await page.getByLabel('Subject',{exact:true}).fill('Budget approval requested');
 await page.locator('#body').fill('## Budget\nPlease review **the totals**.');
 await page.getByLabel('Request acknowledgement',{exact:true}).check();
 await page.getByRole('button',{name:'Send notification',exact:true}).click();
 await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('.detail-title').filter({hasText:'Budget approval requested'}).waitFor();
 await page.getByRole('button',{name:'Sent',exact:false}).click();
 await page.locator('.notification-row').filter({hasText:'Budget approval requested'}).waitFor();
 await page.locator('#settings').click();
 await page.getByLabel('Status',{exact:true}).selectOption('in_a_meeting');
 await page.getByRole('button',{name:'Save status',exact:true}).click();
 await page.locator('#my-status').filter({hasText:'In a meeting'}).waitFor();
 await page.locator('#settings').click();
 await page.getByLabel('Pause duration',{exact:true}).selectOption('30');
 await page.getByRole('button',{name:'Save alert preference',exact:true}).click();
 await page.locator('#dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'New notification'}).click();
 await page.getByLabel('Recipient emails',{exact:true}).fill('alice@example.com, new.colleague@example.com');
 await page.getByLabel('Subject',{exact:true}).fill('Email-addressed handoff');
 await page.locator('#body').fill('A handoff for existing and new colleagues.');
 await page.getByRole('button',{name:'Send notification',exact:true}).click();
 await page.locator('#dialog').waitFor({state:'hidden'});
 await page.locator('.detail-title').filter({hasText:'Email-addressed handoff'}).waitFor();
 await page.locator('.recipient-status').getByText('Awaiting first sign-in',{exact:true}).waitFor();
 await page.locator('.recipient-status').getByText('new.colleague@example.com',{exact:true}).waitFor();
 await page.locator('.recipient-status').getByText('Unread',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Sent',exact:false}).click();
 await page.locator('.notification-row').filter({hasText:'Email-addressed handoff'}).click();
 await page.locator('.recipient-status').getByText('Awaiting first sign-in',{exact:true}).waitFor();
 await page.screenshot({path:process.env.NOTIFYCONTEXT_SCREENSHOT || '/tmp/notifycontext-live-desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Actual-server browser workflow passed: auth, filtered SQL inbox/detail, read, acknowledge, compose, sent, status and pause.');
} finally {await browser.close();}
